apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-bg
  labels:
    app: paymentservice-bg
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: paymentservice-bg
  template:
    metadata:
      labels:
        app: paymentservice-bg
    spec:
      containers:
        - name: server
          image: abvgdeej/paymentservice:v0.0.2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"