apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web #Название Pod
  labels: # Метки в формате key: value
    key: value
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
  - name: hw2-webserver # Название контейнера
    image: i2rdevops/hw2-webserver:latest # Образ из которого создается контейнер
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket:
        port: 8000
    ports:
      - containerPort: 8000
    imagePullPolicy: Always
    volumeMounts:
      - name: app
        mountPath: /app  
  initContainers:
  - name: init
    image: busybox:latest
    imagePullPolicy: Always
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app

  volumes:
    - name: app
      emptyDir: {}
